name: influx-importer-strava

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and deploy container
    runs-on: ubuntu-latest

    steps:
    - name: Build docker image
      run: docker build -t docker.timeseer.ai/influx-importer-strava:latest .

    - name: Login to container registry
      uses: azure/docker-login@v1
      with:
        login-server: docker.timeseer.ai
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push docker image
      run: docker push docker.timeseer.ai/influx-importer-strava:latest
